//go:build ignore

// html_entitygen writes html_entity_table.go, the named character reference
// table of the HTML parser, from the WHATWG list:
//
//	curl -sSO https://html.spec.whatwg.org/entities.json
//	go run html_entitygen.go entities.json > html_entity_table.go
//
// The table is static data (no init work, no map): the names and their
// replacement texts are two string blobs, and an open-addressing hash table of
// entity indexes finds a name with one FNV-1a hash and, usually, one compare.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"os"
	"sort"
	"strings"
)

const tableSize = 4096 // power of two, ~55% load

func hash(s string) uint32 {
	h := uint32(2166136261)
	for i := 0; i < len(s); i++ {
		h = (h ^ uint32(s[i])) * 16777619
	}
	return h
}

func main() {
	raw, err := os.ReadFile(os.Args[1])
	if err != nil {
		panic(err)
	}
	var entities map[string]struct {
		Characters string `json:"characters"`
	}
	if err := json.Unmarshal(raw, &entities); err != nil {
		panic(err)
	}
	names := make([]string, 0, len(entities))
	for name := range entities {
		names = append(names, strings.TrimPrefix(name, "&"))
	}
	sort.Strings(names)

	var nameBlob, valueBlob strings.Builder
	type entry struct{ nameOff, valueOff, nameLen, valueLen int }
	entries := make([]entry, len(names))
	valueAt := map[string]int{}
	maxLen := 0
	for i, name := range names {
		value := entities["&"+name].Characters
		off, ok := valueAt[value]
		if !ok {
			off = valueBlob.Len()
			valueBlob.WriteString(value)
			valueAt[value] = off
		}
		entries[i] = entry{nameBlob.Len(), off, len(name), len(value)}
		nameBlob.WriteString(name)
		maxLen = max(maxLen, len(name))
	}
	if nameBlob.Len() >= 1<<16 || valueBlob.Len() >= 1<<16 || len(names) >= tableSize {
		panic("table does not fit its integer types")
	}
	var table [tableSize]uint16
	for i, name := range names {
		j := hash(name) & (tableSize - 1)
		for table[j] != 0 {
			j = (j + 1) & (tableSize - 1)
		}
		table[j] = uint16(i + 1)
	}

	w := new(bytes.Buffer)
	fmt.Fprintf(w, "// Code generated by html_entitygen.go from the WHATWG entities.json; DO NOT EDIT.\n\npackage truffle\n\n")
	fmt.Fprintf(w, "// entityMaxLen is the longest entity name, \";\" included.\nconst entityMaxLen = %d\n\n", maxLen)
	fmt.Fprintf(w, "const entityTableSize = %d\n\n", tableSize)
	fmt.Fprintf(w, "// entityNameBlob holds the %d names (without \"&\"), sorted, back to back.\n", len(names))
	writeBlob(w, "entityNameBlob", nameBlob.String())
	fmt.Fprintf(w, "// entityValueBlob holds the distinct replacement texts, UTF-8.\n")
	writeBlob(w, "entityValueBlob", valueBlob.String())
	fmt.Fprintf(w, "// entityList is {name offset, value offset, name length, value length} per entity.\n")
	fmt.Fprintf(w, "var entityList = [%d]struct {\n\tnameOff, valueOff uint16\n\tnameLen, valueLen uint8\n}{\n", len(names))
	for i, e := range entries {
		fmt.Fprintf(w, "\t{%d, %d, %d, %d}, // %s\n", e.nameOff, e.valueOff, e.nameLen, e.valueLen, names[i])
	}
	fmt.Fprintf(w, "}\n\n// entityTable maps entityHash slots (linear probing) to entityList index + 1.\n")
	fmt.Fprintf(w, "var entityTable = [entityTableSize]uint16{")
	for i, v := range table {
		if i%16 == 0 {
			fmt.Fprintf(w, "\n\t")
		} else {
			fmt.Fprintf(w, " ")
		}
		fmt.Fprintf(w, "%d,", v)
	}
	fmt.Fprintf(w, "\n}\n")
	src, err := format.Source(w.Bytes())
	if err != nil {
		panic(err)
	}
	os.Stdout.Write(src)
}

func writeBlob(w io.Writer, name, s string) {
	fmt.Fprintf(w, "const %s = \"\" +\n", name)
	for len(s) > 0 {
		n := min(len(s), 64)
		// Do not split a UTF-8 sequence across lines.
		for n < len(s) && s[n]&0xC0 == 0x80 {
			n++
		}
		sep := " +"
		if n == len(s) {
			sep = ""
		}
		fmt.Fprintf(w, "\t%q%s\n", s[:n], sep)
		s = s[n:]
	}
	fmt.Fprintf(w, "\n")
}
