import 'dart:ui' show Color;

import '../../core/theme/theme_presets.dart';

/// The enhancer's theme roles (`--tr-panel`, `--tr-syn-*`, see
/// `themeDeclarations` in apps/web/src/reader/enhance/css.ts) for every
/// preset, for Readium documents.
///
/// Nothing can call the bundle's `setTheme` inside Readium's web views, but
/// ReadiumCSS writes the active paper and ink onto `<html style>` as
/// `--USER__backgroundColor` / `--USER__textColor`, and updates them live.
/// Each preset's roles are therefore keyed on that pair. Readium Swift writes
/// `#RRGGBB`; the `rgb()` forms cover other serialisations. With no match
/// (an unknown theme), the stylesheet's mixes of the text colour apply.
String readiumThemeCss([List<ThemePreset> presets = ThemePreset.all]) {
  final out = StringBuffer(
    '/* GENERATED by the app from its theme presets '
    '(lib/reader/enhance/readium_theme_css.dart). */\n',
  );
  for (final preset in presets) {
    final c = preset.colors;
    final selectors = [
      for (final (paper, ink) in [
        (_hex(c.paper), _hex(c.ink)),
        (_rgb(c.paper, ', '), _rgb(c.ink, ', ')),
        (_rgb(c.paper, ','), _rgb(c.ink, ',')),
      ])
        ':root[style*="$paper" i][style*="$ink" i]',
    ];
    final roles = {
      'panel': c.panel,
      'border': c.border,
      'syn-comment': c.subtle,
      'syn-keyword': c.purple,
      'syn-string': c.green,
      'syn-number': c.orange,
      'syn-title': c.blue,
      'syn-type': c.cyan,
      'syn-attr': c.blue,
      'syn-tag': c.pink,
    };
    out
      ..write('/* ${preset.id} */ ')
      ..write(selectors.join(', '))
      ..write('{')
      ..writeAll([
        for (final e in roles.entries) '--tr-${e.key}:${_hex(e.value)};',
      ])
      ..write('}\n');
  }
  return out.toString();
}

int _rgbOf(Color c) => c.toARGB32() & 0xFFFFFF;

String _hex(Color c) => '#${_rgbOf(c).toRadixString(16).padLeft(6, '0')}';

String _rgb(Color c, String sep) {
  final v = _rgbOf(c);
  return 'rgb(${v >> 16 & 0xff}$sep${v >> 8 & 0xff}$sep${v & 0xff})';
}
