/**
 * Code languages: the article model's ids (highlight.js names, plus `html`
 * and common aliases) to highlight.js grammar names and display labels.
 * `shell` is a console session with prompts, `bash` a script. Kept apart
 * from the highlighter so labels show before its chunk loads.
 */

const aliases: Record<string, string> = {
  js: 'javascript',
  jsx: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  node: 'javascript',
  ts: 'typescript',
  tsx: 'typescript',
  mts: 'typescript',
  py: 'python',
  python3: 'python',
  sh: 'bash',
  zsh: 'bash',
  ksh: 'bash',
  fish: 'bash',
  console: 'shell',
  'shell-session': 'shell',
  shellsession: 'shell',
  terminal: 'shell',
  html: 'xml',
  xhtml: 'xml',
  svg: 'xml',
  vue: 'xml',
  svelte: 'xml',
  jsonc: 'json',
  json5: 'json',
  'c++': 'cpp',
  cc: 'cpp',
  hpp: 'cpp',
  h: 'c',
  cs: 'csharp',
  'c#': 'csharp',
  golang: 'go',
  rs: 'rust',
  rb: 'ruby',
  kt: 'kotlin',
  kts: 'kotlin',
  yml: 'yaml',
  toml: 'ini',
  conf: 'ini',
  cfg: 'ini',
  md: 'markdown',
  mdx: 'markdown',
  patch: 'diff',
  docker: 'dockerfile',
  containerfile: 'dockerfile',
  make: 'makefile',
  mk: 'makefile',
  postgres: 'pgsql',
  postgresql: 'pgsql',
  mysql: 'sql',
  sqlite: 'sql',
  plsql: 'sql',
  tsql: 'sql',
  objc: 'objectivec',
  reason: 'reasonml',
  pascal: 'delphi',
  f90: 'fortran',
  'objective-c': 'objectivec',
  ps1: 'powershell',
  pwsh: 'powershell',
  ex: 'elixir',
  exs: 'elixir',
  hs: 'haskell',
  erl: 'erlang',
  fs: 'fsharp',
  'f#': 'fsharp',
  ml: 'ocaml',
  clj: 'clojure',
  tex: 'latex',
  jl: 'julia',
  pl: 'perl',
  proto: 'protobuf',
  gql: 'graphql',
  asm: 'x86asm',
  nasm: 'x86asm',
  text: 'plaintext',
  txt: 'plaintext',
  plain: 'plaintext',
  none: 'plaintext',
  vb: 'vbnet',
  'vb.net': 'vbnet',
  bat: 'dos',
  cmd: 'dos',
  batch: 'dos',
  wat: 'wasm',
};

/** Grammar names the highlighter can load (see `highlight.ts`). */
export const grammars = [
  'ada', 'apache', 'armasm', 'awk', 'bash', 'c', 'clojure', 'cmake', 'coq', 'cpp', 'crystal', 'csharp', 'css', 'd',
  'dart', 'delphi', 'diff', 'dockerfile', 'dos', 'elixir', 'elm', 'erb', 'erlang', 'fortran', 'fsharp', 'go',
  'graphql', 'groovy', 'haskell', 'haxe', 'http', 'ini', 'java', 'javascript', 'json', 'julia', 'kotlin', 'latex',
  'less', 'lisp', 'lua', 'makefile', 'markdown', 'matlab', 'mipsasm', 'nginx', 'nim', 'nix', 'objectivec', 'ocaml',
  'perl', 'pgsql', 'php', 'plaintext', 'powershell', 'prolog', 'properties', 'protobuf', 'python', 'r', 'reasonml',
  'ruby', 'rust', 'scala', 'scheme', 'scss', 'shell', 'sql', 'stylus', 'swift', 'tcl', 'typescript', 'vala', 'vbnet',
  'vbscript', 'vim', 'wasm', 'x86asm', 'xml', 'yaml',
] as const;

export type Grammar = (typeof grammars)[number];

const known = new Set<string>(grammars);

/** The highlight.js grammar for a language id, or null when none fits. */
export function grammarFor(language: string): Grammar | null {
  const id = language.trim().toLowerCase();
  const name = aliases[id] ?? id;
  return known.has(name) ? (name as Grammar) : null;
}

const labels: Record<string, string> = {
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  jsx: 'JSX',
  tsx: 'TSX',
  python: 'Python',
  bash: 'Shell',
  shell: 'Console',
  xml: 'XML',
  html: 'HTML',
  svg: 'SVG',
  css: 'CSS',
  scss: 'SCSS',
  less: 'Less',
  json: 'JSON',
  c: 'C',
  cpp: 'C++',
  csharp: 'C#',
  go: 'Go',
  rust: 'Rust',
  java: 'Java',
  kotlin: 'Kotlin',
  swift: 'Swift',
  ruby: 'Ruby',
  php: 'PHP',
  sql: 'SQL',
  pgsql: 'PostgreSQL',
  yaml: 'YAML',
  ini: 'INI',
  toml: 'TOML',
  markdown: 'Markdown',
  diff: 'Diff',
  dockerfile: 'Dockerfile',
  makefile: 'Makefile',
  objectivec: 'Objective-C',
  powershell: 'PowerShell',
  graphql: 'GraphQL',
  latex: 'LaTeX',
  matlab: 'MATLAB',
  ocaml: 'OCaml',
  fsharp: 'F#',
  vbnet: 'VB.NET',
  x86asm: 'Assembly',
  wasm: 'WebAssembly',
  http: 'HTTP',
  dos: 'Batch',
  nginx: 'Nginx',
  protobuf: 'Protocol Buffers',
  plaintext: 'Text',
  r: 'R',
  erb: 'ERB',
  awk: 'Awk',
  d: 'D',
  reasonml: 'ReasonML',
  armasm: 'ARM Assembly',
  mipsasm: 'MIPS Assembly',
  vbscript: 'VBScript',
  hcl: 'HCL',
  solidity: 'Solidity',
};

/** "TypeScript", "C++", "Shell"; unknown ids are capitalized. */
export function languageLabel(language: string): string {
  const id = language.trim().toLowerCase();
  return labels[id] ?? labels[aliases[id] ?? ''] ?? id.charAt(0).toUpperCase() + id.slice(1);
}
